import Phaser from "phaser";

/**
 * BootScene — preloads all placeholder assets then hands off to OverworldScene.
 *
 * Asset paths reference files created by Task 4 (placeholder tilemap).
 * The game will show a black screen until those assets exist on disk.
 */
export class BootScene extends Phaser.Scene {
  constructor() {
    super({ key: "BootScene" });
  }

  preload(): void {
    // Bottom-layer metatile tileset (generated by scripts/compose-metatiles.mjs)
    this.load.image(
      "mauville_bottom",
      "/game/tilesets/mauville_bottom.png",
    );

    // Top-layer metatile tileset (renders above player for pseudo-3D)
    this.load.image(
      "mauville_top",
      "/game/tilesets/mauville_top.png",
    );

    // Tiled JSON map (generated by scripts/compose-metatiles.mjs)
    this.load.tilemapTiledJSON(
      "mauville",
      "/game/maps/mauville.json",
    );

    // Brendan spritesheet — 12 frames in a 3x4 grid (48x128 sheet)
    // Layout: Row 0=down, Row 1=left, Row 2=right, Row 3=up
    // Each row: [walk1, stand, walk2]
    this.load.spritesheet("player", "/game/sprites/emerald/brendan.png", {
      frameWidth: 16,
      frameHeight: 32,
    });

    // NPC spritesheets — same 12-frame 3x4 grid layout as Brendan
    const npcSprites = [
      "boy_3",
      "rich_boy",
      "maniac",
      "woman_4",
      "school_kid_m",
      "fat_man",
    ];
    for (const name of npcSprites) {
      this.load.spritesheet(name, `/game/sprites/emerald/${name}.png`, {
        frameWidth: 16,
        frameHeight: 32,
      });
    }

    // Item ball — single 16x16 image (loaded as spritesheet for Grid Engine compat)
    this.load.spritesheet("item_ball", "/game/sprites/emerald/item_ball.png", {
      frameWidth: 16,
      frameHeight: 16,
    });
  }

  create(): void {
    this.scene.start("OverworldScene");
  }
}
