import Phaser from "phaser";
import { bgm } from "@/game/systems/BGMManager";
import { loadInteriorState } from "@/game/systems/InteriorStateStore";
import { WILD_POKEMON_SPECIES } from "@/game/data/wild-pokemon";

/**
 * BootScene — preloads all placeholder assets then hands off to OverworldScene.
 *
 * Asset paths reference files created by Task 4 (placeholder tilemap).
 * The game will show a black screen until those assets exist on disk.
 */
export class BootScene extends Phaser.Scene {
  constructor() {
    super({ key: "BootScene" });
  }

  preload(): void {
    // Composite ground tileset — bottom layer for layerType-0 metatiles,
    // both layers for layerType-1 metatiles. The latter (flowers, etc.)
    // need their top layer in the ground so the player covers them.
    // Layer-type-0 top layers (trees, signs, fences) are in the foreground.
    this.load.image("mauville_bottom", "/game/tilesets/mauville_ground.png");

    // Map name popup backgrounds (OG map_popup assets)
    this.load.image("popup_marble", "/game/ui/popup_marble.png");
    this.load.image("popup_wood", "/game/ui/popup_wood.png");

    // Top-layer-only tileset used by obstructive overlay sprites
    // (signs etc.) so they only draw the object pixels, not grass bg.
    this.load.image("mauville_top", "/game/tilesets/mauville_top.png");

    // Foreground: single pre-rendered PNG of the top layer (renders above player)
    this.load.image("mauville_foreground", "/game/maps/mauville_foreground.png");

    // Tiled JSON map (generated by scripts/compose-metatiles.mjs)
    this.load.tilemapTiledJSON("mauville", "/game/maps/mauville.json");

    // Brendan spritesheet — original pret format: 144x32, 9 frames of 16x32
    // Frames: 0-2 = down, 3-5 = up, 6-8 = left. Right = flipped left.
    this.load.spritesheet("player", "/game/sprites/emerald/brendan.png", {
      frameWidth: 16,
      frameHeight: 32,
    });

    // NPC spritesheets — same 144x32 9-frame format as Brendan.
    // NOTE: DO NOT add sprites with a different frame layout (like
    // little_boy which is 144x16, or old_man which is 48x32). Adding
    // them here with the wrong dimensions causes them to render as
    // a wide strip showing all 9 frames side-by-side — which looks
    // like a row of duplicate NPCs in the scene.
    const npcSprites = [
      "boy_3",
      "rich_boy",
      "maniac",
      "woman_4",
      "school_kid_m",
      "fat_man",
      // Route NPCs (added when routes were stitched in)
      "woman_1",
      "woman_2",
      "lass",
      "girl_2",
      "girl_3",
      "fisherman",
      "youngster",
      "man_1",
      "pokefan_f",
      // Team Magma & Aqua grunts
      "magma_member_m",
      "magma_member_f",
      "aqua_member_m",
      "aqua_member_f",
    ];
    for (const name of npcSprites) {
      this.load.spritesheet(name, `/game/sprites/emerald/${name}.png`, {
        frameWidth: 16,
        frameHeight: 32,
      });
    }

    // Item ball — single 16x16 image (loaded as spritesheet for Grid Engine compat)
    this.load.spritesheet("item_ball", "/game/sprites/emerald/item_ball.png", {
      frameWidth: 16,
      frameHeight: 16,
    });

    // Snorlax blocker — 32x32 single frame (static, doesn't animate).
    // Sourced from pokeemerald's big_snorlax_doll.png. It occupies 2x2
    // tile visual footprint but only sits on 1 grid tile (collision).
    this.load.spritesheet("snorlax", "/game/sprites/emerald/snorlax.png", {
      frameWidth: 32,
      frameHeight: 32,
    });

    // Slaking — 48x48 Lanczos from 64x64 (75%), rendered at scale 2/3 = 32px.
    this.load.spritesheet("slaking", "/game/sprites/emerald/slaking.png", {
      frameWidth: 48,
      frameHeight: 48,
    });

    // Slakoth — 48x48 Lanczos from 64x64 (75%), rendered at scale 2/3 = 32px.
    this.load.spritesheet("slakoth", "/game/sprites/emerald/slakoth.png", {
      frameWidth: 48,
      frameHeight: 48,
    });

    // Poochyena overworld — 288x32, 9 frames of 32x32 (same layout as NPCs).
    // Used by both Team Aqua and Magma in cutscenes.
    this.load.spritesheet("poochyena_ow", "/game/sprites/emerald/poochyena_ow.png", {
      frameWidth: 32,
      frameHeight: 32,
    });

    // Tall grass overlay — 80x16, 5 frames of 16x16.
    // OG field effect: renders on top of player's lower body in grass.
    this.load.spritesheet("tall_grass", "/game/sprites/emerald/tall_grass.png", {
      frameWidth: 16,
      frameHeight: 16,
    });

    // Nurse Joy — 64x32 = 4 frames of 16x32 (down, up, left, right standing).
    // Not 9-frame like standard NPCs. Used as non-animated (stationary facing down).
    this.load.spritesheet("nurse", "/game/sprites/emerald/nurse.png", {
      frameWidth: 16,
      frameHeight: 32,
    });

    // Old Man (day care guy) — 48x32 = 3 frames of 16x32.
    // Loaded as 3-frame spritesheet to match the actual file size.
    // Used as a non-animated NPC (Grid Engine won't use walk animation
    // since the mapping expects 9 frames).
    this.load.spritesheet("old_man", "/game/sprites/emerald/old_man.png", {
      frameWidth: 16,
      frameHeight: 32,
    });

    // Wild Pokemon overworld sprites — party-style icons (32x64, 2 frames).
    // Frame 0 = normal, Frame 1 = bounce. Used for idle animation on the map.
    for (const species of WILD_POKEMON_SPECIES) {
      this.load.spritesheet(`pkmn_${species}`, `/game/sprites/pokemon/icons/${species}.png`, {
        frameWidth: 32,
        frameHeight: 32,
      });
    }
  }

  create(): void {
    // Wait for BGM to preload before starting the overworld.
    // This ensures music can play instantly when the scene starts.
    bgm.preloadAll().then(() => {
      // Check if player was saved inside a building
      const interior = loadInteriorState();
      if (interior) {
        this.scene.start("InteriorScene", {
          interiorKey: interior.interiorKey,
          returnPos: null, // will use overworld save for return
          spawnPos: { x: interior.x, y: interior.y },
          spawnFacing: interior.facing,
        });
      } else {
        this.scene.start("OverworldScene");
      }
    });
  }
}
