import Phaser from "phaser";

/**
 * BootScene — preloads all placeholder assets then hands off to OverworldScene.
 *
 * Asset paths reference files created by Task 4 (placeholder tilemap).
 * The game will show a black screen until those assets exist on disk.
 */
export class BootScene extends Phaser.Scene {
  constructor() {
    super({ key: "BootScene" });
  }

  preload(): void {
    // Composed metatile tileset (generated by scripts/compose-metatiles.mjs)
    this.load.image(
      "mauville_composed",
      "/game/tilesets/mauville_composed.png",
    );

    // Tiled JSON map (generated by scripts/compose-metatiles.mjs)
    this.load.tilemapTiledJSON(
      "mauville",
      "/game/maps/mauville.json",
    );

    // Player spritesheet — 16x16 frames, 4 directions x 3 walk frames
    this.load.spritesheet("player", "/game/sprites/player.png", {
      frameWidth: 16,
      frameHeight: 16,
    });
  }

  create(): void {
    this.scene.start("OverworldScene");
  }
}
