import Phaser from "phaser";
import {
  emitEditorEvent,
  onEditorEvent,
  ENTITY_CLICKED,
  ENTITY_HOVERED,
  TILE_CLICKED,
  MOUSE_MOVE,
  DRAG_START,
  DRAG_MOVE,
  DRAG_END,
  VIEWPORT_READY,
  SELECT_ENTITY,
  DESELECT,
  TOGGLE_LAYER,
  UPDATE_ENTITY_POSITION,
  UPDATE_ENTITY_FIELD,
  ADD_ENTITY_MARKER,
  REMOVE_ENTITY_MARKER,
  JUMP_TO_TILE,
  REFRESH_ENTITIES,
  SWITCH_MAP,
  SET_TOOL,
} from "../editor/EditorEvents";

const TILE_SIZE = 16;
let MAP_WIDTH = 140;
let MAP_HEIGHT = 120;

interface MapConfig {
  key: string;
  mapJson: string;
  tilesetName: string;
  tilesetImage: string;
  tilesetTop?: string;
  foreground?: string;
  width: number;
  height: number;
}

const MAP_CONFIGS: Record<string, MapConfig> = {
  // Editor uses the decor-only foreground (grass/dirt pixels stripped so
  // trees/fences/rocks can be tinted without also tinting the grass around them).
  // Generated by `scripts/split-foreground-layers.mjs`.
  mauville: { key: "mauville-map", mapJson: "/game/maps/mauville.json", tilesetName: "mauville_bottom", tilesetImage: "/game/tilesets/mauville_bottom.png", foreground: "/game/maps/mauville_foreground_decor.png", width: 140, height: 120 },
  pokecenter: { key: "pokecenter-map", mapJson: "/game/maps/pokecenter.json", tilesetName: "pokecenter_bottom", tilesetImage: "/game/tilesets/pokecenter_bottom.png", tilesetTop: "/game/tilesets/pokecenter_top.png", width: 14, height: 9 },
  mart: { key: "mart-map", mapJson: "/game/maps/mart.json", tilesetName: "mart_bottom", tilesetImage: "/game/tilesets/mart_bottom.png", tilesetTop: "/game/tilesets/mart_top.png", width: 11, height: 8 },
  gym: { key: "gym-map", mapJson: "/game/maps/gym.json", tilesetName: "gym_bottom", tilesetImage: "/game/tilesets/gym_bottom.png", tilesetTop: "/game/tilesets/gym_top.png", width: 10, height: 21 },
};
const MIN_ZOOM = 0.3;
const MAX_ZOOM = 6;
const ZOOM_SPEED = 0.08; // smooth zoom per scroll tick
const DEFAULT_ZOOM = 1.5;

interface EntityMarker {
  id: string;
  type: string;
  x: number;
  y: number;
  spriteKey?: string;
  movementRangeX?: number;
  movementRangeY?: number;
  container: Phaser.GameObjects.Container;
  shape: Phaser.GameObjects.Graphics;
  sprite?: Phaser.GameObjects.Sprite;
  selectionRing?: Phaser.GameObjects.Graphics;
}

const TYPE_COLORS: Record<string, number> = {
  npc: 0x3b82f6,
  "pokemon-npc": 0x06b6d4,
  pickup: 0xf97316,
  "wild-pokemon": 0x22c55e,
  sign: 0xf59e0b,
  "hidden-item": 0xec4899,
  warp: 0x8b5cf6,
  gate: 0xdc2626,
};

export class EditorScene extends Phaser.Scene {
  private markers: Map<string, EntityMarker> = new Map();
  private selectedId: string | null = null;
  private currentZoom: number = DEFAULT_ZOOM;
  private isPanning: boolean = false;
  private panMoved: boolean = false;
  private panStart: { x: number; y: number } = { x: 0, y: 0 };
  private camStart: { x: number; y: number } = { x: 0, y: 0 };
  private spaceDown: boolean = false;
  private isDragging: boolean = false;
  private dragEntityId: string | null = null;
  private dragGhost: Phaser.GameObjects.Graphics | null = null;
  // dragTimer removed — drag starts instantly on selected entities
  private coordText!: Phaser.GameObjects.Text;
  private gridGraphics: Phaser.GameObjects.Graphics | null = null;
  private collisionOverlay: Phaser.GameObjects.Graphics | null = null;
  private movementGraphics: Phaser.GameObjects.Graphics | null = null;
  private gridVisible: boolean = false;
  private collisionVisible: boolean = false;
  private movementVisible: boolean = false;
  private tilemap: Phaser.Tilemaps.Tilemap | null = null;
  private groundLayer: Phaser.Tilemaps.TilemapLayer | null = null;
  private collisionLayerData: number[] = [];
  private foregroundImage: Phaser.GameObjects.Image | null = null;
  private topSprites: Phaser.GameObjects.Sprite[] = [];
  private tintHighlights: Map<string, { gfx: Phaser.GameObjects.Graphics; tween: Phaser.Tweens.Tween }> = new Map();
  private foregroundVisible: boolean = true;
  private hoverTooltip: Phaser.GameObjects.Container | null = null;
  private unsubscribers: (() => void)[] = [];
  private selectedTileGid: number = 0;
  private currentTool: string = "select";
  // Block copy/paste state
  private blockSelection: { startX: number; startY: number; endX: number; endY: number; tiles: number[][] } | null = null;
  private blockSelectionGraphics: Phaser.GameObjects.Graphics | null = null;
  private isShiftDragging: boolean = false;
  private shiftDragStart: { x: number; y: number } | null = null;

  constructor() {
    super({ key: "EditorScene" });
  }

  private currentMapId: string = "mauville";

  preload(): void {
    // Preload all map configs
    for (const [, cfg] of Object.entries(MAP_CONFIGS)) {
      this.load.tilemapTiledJSON(cfg.key, cfg.mapJson);
      this.load.image(cfg.tilesetName, cfg.tilesetImage);
      if (cfg.foreground) this.load.image(cfg.tilesetName + "_fg", cfg.foreground);
      if (cfg.tilesetTop) this.load.image(cfg.tilesetName.replace("_bottom", "_top"), cfg.tilesetTop);
    }

    // NPC spritesheets — load ALL sprites from /game/sprites/emerald/
    // Load every sprite so the user can switch any NPC to any sprite via dropdown.
    const SPECIAL_SIZES: Record<string, { w: number; h: number }> = {
      slakoth: { w: 48, h: 48 },
      slaking: { w: 48, h: 48 },
      item_ball: { w: 16, h: 16 },
      tall_grass: { w: 16, h: 16 },
      little_boy: { w: 16, h: 16 },
      little_girl: { w: 16, h: 16 },
      scott: { w: 48, h: 128 },
      wally: { w: 48, h: 128 },
    };
    // Fetch the full sprite list from editor-data.json and preload all of them.
    // This runs during Phaser's preload phase, which supports async loading.
    this.load.json("editor-data-sprites", "/api/editor/data");
    this.load.once("filecomplete-json-editor-data-sprites", () => {
      const data = this.cache.json.get("editor-data-sprites");
      const spriteList: string[] = data?.availableSprites?.npcs || [];
      for (const key of spriteList) {
        if (this.textures.exists(`npc_${key}`)) continue;
        const special = SPECIAL_SIZES[key];
        if (special) {
          if (special.w <= 16 && special.h <= 16) {
            this.load.image(`npc_${key}`, `/game/sprites/emerald/${key}.png`);
          } else {
            this.load.spritesheet(`npc_${key}`, `/game/sprites/emerald/${key}.png`, {
              frameWidth: special.w, frameHeight: special.h,
            });
          }
        } else {
          this.load.spritesheet(`npc_${key}`, `/game/sprites/emerald/${key}.png`, {
            frameWidth: 16, frameHeight: 32,
          });
        }
      }
    });

    // Pokemon icon sprites (from /game/sprites/pokemon/icons/)
    const pokemonIcons = [
      "absol", "aggron", "altaria", "banette", "blaziken", "breloom",
      "camerupt", "claydol", "delcatty", "flygon", "glalie", "kirlia",
      "kyogre", "lairon", "latias", "manectric", "mawile", "medicham",
      "pelipper", "plusle", "sableye", "salamence", "seviper", "shedinja",
      "solrock", "swellow", "torkoal", "trapinch", "vibrava", "volbeat", "wailord",
    ];
    for (const name of pokemonIcons) {
      this.load.spritesheet(`pkmn_icon_${name}`, `/game/sprites/pokemon/icons/${name}.png`, {
        frameWidth: 32,
        frameHeight: 32,
      });
    }
  }

  create(): void {
    // Create tilemap
    this.tilemap = this.make.tilemap({ key: "mauville-map" });
    // Phaser reads margin/spacing from the Tiled JSON automatically
    const tileset = this.tilemap.addTilesetImage("mauville_bottom", "mauville_bottom");
    if (tileset) {
      this.groundLayer = this.tilemap.createLayer("Ground", tileset, 0, 0);
      // Store collision layer data for overlay rendering
      const collLayer = this.tilemap.getLayer("Collision");
      if (collLayer) {
        this.collisionLayerData = collLayer.data.flat().map((t) => t.index);
      }
    }

    // Foreground — render as per-tile sprites (not a flat image) so each
    // tree/fence/rock/flower can be individually tinted by the Tint tool.
    this.createOverworldForegroundTiles();

    // Camera setup
    const cam = this.cameras.main;
    cam.setBounds(0, 0, MAP_WIDTH * TILE_SIZE, MAP_HEIGHT * TILE_SIZE);
    cam.setZoom(this.currentZoom);
    cam.centerOn((MAP_WIDTH * TILE_SIZE) / 2, (MAP_HEIGHT * TILE_SIZE) / 2);

    // Coordinate display
    this.coordText = this.add.text(8, 8, "Tile: (0, 0)", {
      fontFamily: "monospace",
      fontSize: "12px",
      color: "#ffffff",
      backgroundColor: "#00000099",
      padding: { x: 4, y: 2 },
    });
    this.coordText.setScrollFactor(0);
    this.coordText.setDepth(1000);

    // Input setup
    this.setupInput();

    // Listen for React events
    this.setupEventListeners();

    // Emit ready after create() fully completes (next tick)
    this.time.delayedCall(0, () => {
      emitEditorEvent(VIEWPORT_READY, {});
    });
  }

  private setupInput(): void {
    const cam = this.cameras.main;

    // Space key for pan
    this.input.keyboard?.on("keydown-SPACE", () => {
      this.spaceDown = true;
    });
    this.input.keyboard?.on("keyup-SPACE", () => {
      this.spaceDown = false;
    });

    // Scroll wheel zoom — smooth continuous zoom
    this.input.on("wheel", (_pointer: any, _gameObjects: any, _deltaX: number, deltaY: number) => {
      const factor = deltaY > 0 ? (1 - ZOOM_SPEED) : (1 + ZOOM_SPEED);
      this.currentZoom = Math.max(MIN_ZOOM, Math.min(MAX_ZOOM, this.currentZoom * factor));
      cam.setZoom(this.currentZoom);
    });

    // Pointer down
    this.input.on("pointerdown", (pointer: Phaser.Input.Pointer) => {
      // Middle-click or space+left-click: start panning
      if (pointer.middleButtonDown() || (this.spaceDown && pointer.leftButtonDown())) {
        this.isPanning = true;
        this.panStart = { x: pointer.x, y: pointer.y };
        this.camStart = { x: cam.scrollX, y: cam.scrollY };
        return;
      }

      // Right-click (handled by interaction for context menu)
      if (pointer.rightButtonDown()) return;

      // Left-click: tool-dependent behavior
      if (pointer.leftButtonDown()) {
        const worldX = pointer.worldX;
        const worldY = pointer.worldY;
        const tileX = Math.floor(worldX / TILE_SIZE);
        const tileY = Math.floor(worldY / TILE_SIZE);

        // Shift+drag: start block selection for copy/paste
        if (this.input.keyboard?.checkDown(this.input.keyboard.addKey("SHIFT")) && this.tilemap) {
          this.isShiftDragging = true;
          this.shiftDragStart = { x: tileX, y: tileY };
          return;
        }

        // Ctrl+click: toggle collision on this tile
        if (this.input.keyboard?.checkDown(this.input.keyboard.addKey("CTRL")) && this.tilemap) {
          const idx = tileY * MAP_WIDTH + tileX;
          if (idx >= 0 && idx < this.collisionLayerData.length) {
            const wasBlocked = this.collisionLayerData[idx] > 0;
            this.collisionLayerData[idx] = wasBlocked ? 0 : 1;
            // Update the collision layer in tilemap
            const collLayer = this.tilemap.getLayer("Collision");
            if (collLayer) {
              this.tilemap.putTileAt(wasBlocked ? 0 : 1, tileX, tileY, false, "Collision");
            }
            // Re-render collision overlay if visible
            if (this.collisionVisible) this.renderCollisionOverlay();
            emitEditorEvent("editor:collision-toggle", { x: tileX, y: tileY, blocked: !wasBlocked });
          }
          return;
        }

        // Stamp tool: paste block or paint single tile
        if (this.currentTool === "stamp" && this.tilemap) {
          if (this.blockSelection && this.blockSelection.tiles.length > 0) {
            // Paste copied block at cursor position
            const { tiles } = this.blockSelection;
            for (let dy = 0; dy < tiles.length; dy++) {
              for (let dx = 0; dx < tiles[dy].length; dx++) {
                if (tiles[dy][dx] > 0) {
                  this.tilemap.putTileAt(tiles[dy][dx], tileX + dx, tileY + dy, false, "Ground");
                }
              }
            }
            emitEditorEvent("editor:block-pasted", { x: tileX, y: tileY, w: tiles[0].length, h: tiles.length });
            return;
          }
          if (this.selectedTileGid > 0) {
            this.tilemap.putTileAt(this.selectedTileGid, tileX, tileY, false, "Ground");
            emitEditorEvent("editor:tile-paint", { x: tileX, y: tileY, gid: this.selectedTileGid });
          }
          return;
        }

        // Eyedropper tool: pick tile GID
        if (this.currentTool === "eyedropper" && this.tilemap) {
          const tile = this.tilemap.getTileAt(tileX, tileY, false, "Ground");
          if (tile) {
            this.selectedTileGid = tile.index;
            emitEditorEvent("editor:tile-eyedrop", { gid: tile.index, x: tileX, y: tileY });
            // Auto-switch to stamp tool after picking
            this.currentTool = "stamp";
            emitEditorEvent(SET_TOOL, { tool: "stamp" });
          }
          return;
        }

        // Eraser tool: clear tile
        if (this.currentTool === "eraser" && this.tilemap) {
          this.tilemap.putTileAt(0, tileX, tileY, false, "Ground");
          emitEditorEvent("editor:tile-paint", { x: tileX, y: tileY, gid: 0 });
          return;
        }

        // Tint tool: open color adjust popup for clicked tile.
        // Detects topmost non-ground element (top sprite) or falls back to ground.
        if (this.currentTool === "tint") {
          // Check if there's a top sprite at this tile
          const hasTopSprite = this.topSprites.some((s) => {
            const sx = Math.floor((s.x as number) / TILE_SIZE);
            const sy = Math.floor((s.y as number) / TILE_SIZE);
            return sx === tileX && sy === tileY;
          });
          const layer = hasTopSprite ? "top" : "ground";
          // Detect Shift via multiple sources — browser event, Phaser keyboard state.
          const evt = pointer.event as MouseEvent | PointerEvent | KeyboardEvent | undefined;
          const kbShiftKey = this.input.keyboard?.addKey(Phaser.Input.Keyboard.KeyCodes.SHIFT).isDown;
          const append = !!(evt && (evt as MouseEvent).shiftKey) || !!kbShiftKey;
          if (append) {
            this.addTintHighlight(tileX, tileY);
          } else {
            this.showTintHighlight(tileX, tileY); // resets and sets one
          }
          emitEditorEvent("editor:tint-click", {
            x: tileX,
            y: tileY,
            layer,
            screenX: pointer.x,
            screenY: pointer.y,
            append,
          });
          return;
        }

        // Check for entity hit
        let hitEntity: EntityMarker | null = null;
        let minDist = Infinity;
        for (const marker of this.markers.values()) {
          const mx = marker.x * TILE_SIZE + TILE_SIZE / 2;
          const my = marker.y * TILE_SIZE + TILE_SIZE / 2;
          const dist = Math.sqrt((worldX - mx) ** 2 + (worldY - my) ** 2);
          if (dist < 12 && dist < minDist) {
            hitEntity = marker;
            minDist = dist;
          }
        }

        if (hitEntity) {
          emitEditorEvent(ENTITY_CLICKED, {
            entityId: hitEntity.id,
            entityType: hitEntity.type,
            x: hitEntity.x,
            y: hitEntity.y,
          });

          // Start drag immediately on selected entity
          if (this.selectedId === hitEntity.id) {
            this.isDragging = true;
            this.dragEntityId = hitEntity.id;
            // Dim the original marker to show it's being dragged
            const dragMarker = this.markers.get(hitEntity.id);
            if (dragMarker) dragMarker.container.setAlpha(0.3);
            emitEditorEvent(DRAG_START, { entityId: hitEntity.id });
          }
        } else {
          // No entity hit — start panning with left-click drag
          this.isPanning = true;
          this.panMoved = false;
          this.panStart = { x: pointer.x, y: pointer.y };
          this.camStart = { x: cam.scrollX, y: cam.scrollY };
        }
      }
    });

    // Pointer move
    this.input.on("pointermove", (pointer: Phaser.Input.Pointer) => {
      // Block selection drag
      if (this.isShiftDragging && this.shiftDragStart) {
        const endX = Math.floor(pointer.worldX / TILE_SIZE);
        const endY = Math.floor(pointer.worldY / TILE_SIZE);
        // Draw selection rectangle
        if (this.blockSelectionGraphics) this.blockSelectionGraphics.destroy();
        this.blockSelectionGraphics = this.add.graphics();
        this.blockSelectionGraphics.setDepth(500);
        const sx = Math.min(this.shiftDragStart.x, endX);
        const sy = Math.min(this.shiftDragStart.y, endY);
        const w = Math.abs(endX - this.shiftDragStart.x) + 1;
        const h = Math.abs(endY - this.shiftDragStart.y) + 1;
        this.blockSelectionGraphics.lineStyle(2, 0x4a9eed, 0.8);
        this.blockSelectionGraphics.strokeRect(sx * TILE_SIZE, sy * TILE_SIZE, w * TILE_SIZE, h * TILE_SIZE);
        this.blockSelectionGraphics.fillStyle(0x4a9eed, 0.1);
        this.blockSelectionGraphics.fillRect(sx * TILE_SIZE, sy * TILE_SIZE, w * TILE_SIZE, h * TILE_SIZE);
        return;
      }

      // Panning (left-click drag, middle-click drag, or space+drag)
      if (this.isPanning) {
        const dx = this.panStart.x - pointer.x;
        const dy = this.panStart.y - pointer.y;
        if (Math.abs(dx) > 3 || Math.abs(dy) > 3) this.panMoved = true;
        cam.scrollX = this.camStart.x + dx / cam.zoom;
        cam.scrollY = this.camStart.y + dy / cam.zoom;
        return;
      }

      // Dragging entity
      if (this.isDragging && this.dragEntityId) {
        const tileX = Math.floor(pointer.worldX / TILE_SIZE);
        const tileY = Math.floor(pointer.worldY / TILE_SIZE);
        this.updateDragGhost(tileX, tileY);
        emitEditorEvent(DRAG_MOVE, { entityId: this.dragEntityId, tileX, tileY });
      }

      // Hover detection
      const worldX = pointer.worldX;
      const worldY = pointer.worldY;
      let hoveredEntity: EntityMarker | null = null;
      let minDist = Infinity;
      for (const marker of this.markers.values()) {
        const mx = marker.x * TILE_SIZE + TILE_SIZE / 2;
        const my = marker.y * TILE_SIZE + TILE_SIZE / 2;
        const dist = Math.sqrt((worldX - mx) ** 2 + (worldY - my) ** 2);
        if (dist < 14 && dist < minDist) {
          hoveredEntity = marker;
          minDist = dist;
        }
      }

      if (hoveredEntity) {
        this.showTooltip(hoveredEntity, pointer.worldX, pointer.worldY);
        emitEditorEvent(ENTITY_HOVERED, {
          entityId: hoveredEntity.id,
          entityType: hoveredEntity.type,
          x: hoveredEntity.x,
          y: hoveredEntity.y,
        });
      } else {
        this.hideTooltip();
        emitEditorEvent(ENTITY_HOVERED, null);
      }
    });

    // Handle block selection end
    this.input.on("pointerup", (p: Phaser.Input.Pointer) => {
      if (this.isShiftDragging && this.shiftDragStart && this.tilemap) {
        const endX = Math.floor(p.worldX / TILE_SIZE);
        const endY = Math.floor(p.worldY / TILE_SIZE);
        const sx = Math.min(this.shiftDragStart.x, endX);
        const sy = Math.min(this.shiftDragStart.y, endY);
        const w = Math.abs(endX - this.shiftDragStart.x) + 1;
        const h = Math.abs(endY - this.shiftDragStart.y) + 1;

        // Capture tile GIDs in the selected region
        const tiles: number[][] = [];
        for (let dy = 0; dy < h; dy++) {
          const row: number[] = [];
          for (let dx = 0; dx < w; dx++) {
            const tile = this.tilemap.getTileAt(sx + dx, sy + dy, false, "Ground");
            row.push(tile?.index || 0);
          }
          tiles.push(row);
        }

        this.blockSelection = { startX: sx, startY: sy, endX: sx + w - 1, endY: sy + h - 1, tiles };
        this.isShiftDragging = false;
        this.shiftDragStart = null;

        // Auto-switch to stamp tool for pasting
        this.currentTool = "stamp";
        emitEditorEvent("editor:set-tool", { tool: "stamp" });
        emitEditorEvent("editor:block-copied", { width: w, height: h, tileCount: w * h });
        return;
      }
    });

    // Pointer up outside (pointer leaves canvas while dragging)
    this.input.on("pointerupoutside", () => {
      this.isPanning = false;
      this.panMoved = false;
      this.isDragging = false;
      this.dragEntityId = null;
      this.clearDragGhost();
    });

    // Pointer up
    this.input.on("pointerup", (pointer: Phaser.Input.Pointer) => {
      if (this.isPanning) {
        const wasPanMove = this.panMoved;
        this.isPanning = false;
        this.panMoved = false;
        // If user just clicked without dragging, deselect
        if (!wasPanMove) {
          const tileX = Math.floor(pointer.worldX / TILE_SIZE);
          const tileY = Math.floor(pointer.worldY / TILE_SIZE);
          emitEditorEvent(TILE_CLICKED, { x: tileX, y: tileY });
          emitEditorEvent(ENTITY_CLICKED, { entityId: null });
        }
        return;
      }


      if (this.isDragging && this.dragEntityId) {
        const tileX = Math.floor(pointer.worldX / TILE_SIZE);
        const tileY = Math.floor(pointer.worldY / TILE_SIZE);
        emitEditorEvent(DRAG_END, { entityId: this.dragEntityId, tileX, tileY });
        this.clearDragGhost();
        this.isDragging = false;
        this.dragEntityId = null;
      }
    });

    // Double-click: center on tile
    this.input.on("pointerdown", (pointer: Phaser.Input.Pointer) => {
      if (pointer.leftButtonDown() && pointer.getDuration() < 300) {
        // Check for double click (Phaser doesn't have built-in)
      }
    });

    // Arrow keys for panning
    this.input.keyboard?.on("keydown-LEFT", () => {
      if (!this.selectedId) cam.scrollX -= 32 / cam.zoom;
    });
    this.input.keyboard?.on("keydown-RIGHT", () => {
      if (!this.selectedId) cam.scrollX += 32 / cam.zoom;
    });
    this.input.keyboard?.on("keydown-UP", () => {
      if (!this.selectedId) cam.scrollY -= 32 / cam.zoom;
    });
    this.input.keyboard?.on("keydown-DOWN", () => {
      if (!this.selectedId) cam.scrollY += 32 / cam.zoom;
    });
  }

  private setupEventListeners(): void {
    this.unsubscribers.push(
      onEditorEvent(SELECT_ENTITY, (detail: { entityId: string }) => {
        this.selectEntity(detail.entityId);
      }),
      onEditorEvent(DESELECT, () => {
        this.clearSelection();
      }),
      onEditorEvent(TOGGLE_LAYER, (detail: { layer: string; visible: boolean }) => {
        this.toggleLayer(detail.layer, detail.visible);
      }),
      onEditorEvent(UPDATE_ENTITY_POSITION, (detail: { entityId: string; x: number; y: number }) => {
        this.updateMarkerPosition(detail.entityId, detail.x, detail.y);
      }),
      onEditorEvent(UPDATE_ENTITY_FIELD, (detail: { entityId: string; field: string; value: any }) => {
        this.updateMarkerField(detail.entityId, detail.field, detail.value);
      }),
      onEditorEvent(ADD_ENTITY_MARKER, (detail: { entity: any }) => {
        this.addMarker(detail.entity);
      }),
      onEditorEvent(REMOVE_ENTITY_MARKER, (detail: { entityId: string }) => {
        this.removeMarker(detail.entityId);
      }),
      onEditorEvent(JUMP_TO_TILE, (detail: { x: number; y: number }) => {
        this.cameras.main.centerOn(
          detail.x * TILE_SIZE + TILE_SIZE / 2,
          detail.y * TILE_SIZE + TILE_SIZE / 2,
        );
      }),
      onEditorEvent(REFRESH_ENTITIES, (detail: { entities: any[] }) => {
        this.refreshAllMarkers(detail.entities);
      }),
      onEditorEvent(SWITCH_MAP, (detail: { mapId: string }) => {
        this.switchMap(detail.mapId);
      }),
      onEditorEvent(SET_TOOL, (detail: { tool: string }) => {
        this.currentTool = detail.tool;
        if (detail.tool !== "tint") this.clearTintHighlight();
      }),
      onEditorEvent("editor:tint-close", () => {
        this.clearTintHighlight();
      }),
      onEditorEvent("editor:apply-tile-tint", (detail: { x: number; y: number; layer: string; rgb: number | null; alpha: number }) => {
        this.applySingleTileTint(detail.x, detail.y, detail.layer, detail.rgb, detail.alpha);
      }),
      onEditorEvent("editor:refresh-tints", () => {
        this.refreshAllTints();
      }),
      onEditorEvent("editor:select-tile-gid", (detail: { gid: number }) => {
        this.selectedTileGid = detail.gid;
      }),
    );
  }

  /** Switch to a different map (overworld or interior) */
  private switchMap(mapId: string): void {
    const cfg = MAP_CONFIGS[mapId];
    if (!cfg) return;

    this.currentMapId = mapId;
    MAP_WIDTH = cfg.width;
    MAP_HEIGHT = cfg.height;

    // Destroy existing tilemap layers and top sprites
    if (this.groundLayer) { this.groundLayer.destroy(); this.groundLayer = null; }
    if (this.foregroundImage) { this.foregroundImage.destroy(); this.foregroundImage = null; }
    if (this.collisionOverlay) { this.collisionOverlay.destroy(); this.collisionOverlay = null; }
    if (this.gridGraphics) { this.gridGraphics.destroy(); this.gridGraphics = null; }
    for (const s of this.topSprites) s.destroy();
    this.topSprites = [];

    // Create new tilemap
    this.tilemap = this.make.tilemap({ key: cfg.key });
    const tileset = this.tilemap.addTilesetImage(cfg.tilesetName, cfg.tilesetName);
    if (tileset) {
      this.groundLayer = this.tilemap.createLayer("Ground", tileset, 0, 0);
      const collLayer = this.tilemap.getLayer("Collision");
      if (collLayer) {
        this.collisionLayerData = collLayer.data.flat().map((t) => t.index);
      }
    }

    // Top-layer sprites for interior maps (furniture, desks, stairs, etc.)
    const topKey = cfg.tilesetName.replace("_bottom", "_top");
    if (cfg.tilesetTop && this.textures.exists(topKey) && tileset) {
      const topTex = this.textures.get(topKey);
      const groundData = this.tilemap.getLayer("Ground")?.data;
      if (groundData) {
        const tW = tileset.tileWidth;
        const tH = tileset.tileHeight;
        const margin = (tileset as any).tileMargin ?? 1;
        const spacing = (tileset as any).tileSpacing ?? 2;
        const cols = tileset.columns;

        for (let ty = 0; ty < this.tilemap.height; ty++) {
          for (let tx = 0; tx < this.tilemap.width; tx++) {
            const tile = groundData[ty]?.[tx];
            if (!tile || tile.index <= 0) continue;
            const tileIdx = tile.index - 1;
            const srcCol = tileIdx % cols;
            const srcRow = Math.floor(tileIdx / cols);
            const srcX = margin + srcCol * (tW + spacing);
            const srcY = margin + srcRow * (tH + spacing);

            const frameKey = `${topKey}_${tileIdx}`;
            if (!topTex.has(frameKey)) {
              topTex.add(frameKey, 0, srcX, srcY, tW, tH);
            }

            const sprite = this.add.sprite(tx * tW + tW / 2, ty * tH + tH / 2, topKey, frameKey);
            sprite.setDepth(50 + ty);
            this.topSprites.push(sprite);
          }
        }
      }
    }

    // Foreground for this map (overworld — per-tile sprites for tinting)
    if (cfg.foreground) {
      this.createOverworldForegroundTiles();
    }

    // Update camera bounds
    const cam = this.cameras.main;
    cam.setBounds(0, 0, MAP_WIDTH * TILE_SIZE, MAP_HEIGHT * TILE_SIZE);
    cam.centerOn((MAP_WIDTH * TILE_SIZE) / 2, (MAP_HEIGHT * TILE_SIZE) / 2);

    // Reset zoom for small maps, and fit to viewport
    if (MAP_WIDTH < 30) {
      // Calculate zoom to fit the map within the viewport with some padding
      const viewW = this.scale.width;
      const viewH = this.scale.height;
      const mapPixelW = MAP_WIDTH * TILE_SIZE;
      const mapPixelH = MAP_HEIGHT * TILE_SIZE;
      const fitZoom = Math.min(viewW / mapPixelW, viewH / mapPixelH) * 0.85;
      this.currentZoom = Math.max(2, Math.min(6, fitZoom));
      cam.setZoom(this.currentZoom);
    }

    // Clear entity markers (will be refreshed by React)
    this.refreshAllMarkers([]);
  }

  private lastEmittedTile = "";

  update(): void {
    // Update coordinate display with tile GID info
    const pointer = this.input.activePointer;
    if (pointer) {
      const tileX = Math.floor(pointer.worldX / TILE_SIZE);
      const tileY = Math.floor(pointer.worldY / TILE_SIZE);
      const clampedX = Math.max(0, Math.min(MAP_WIDTH - 1, tileX));
      const clampedY = Math.max(0, Math.min(MAP_HEIGHT - 1, tileY));

      // Get tile GID from tilemap
      let gidInfo = "";
      let groundGid = 0;
      let topSpriteAt = false;
      if (this.tilemap) {
        const groundTile = this.tilemap.getTileAt(clampedX, clampedY, false, "Ground");
        if (groundTile) { gidInfo = ` GID:${groundTile.index}`; groundGid = groundTile.index; }
        const isCollision = this.collisionLayerData[clampedY * MAP_WIDTH + clampedX] > 0;
        if (isCollision) gidInfo += " [BLOCKED]";
      }
      // Detect top sprite at hover
      topSpriteAt = this.topSprites.some((s) => {
        const sx = Math.floor((s.x as number) / TILE_SIZE);
        const sy = Math.floor((s.y as number) / TILE_SIZE);
        return sx === clampedX && sy === clampedY;
      });

      this.coordText.setText(`Tile: (${clampedX}, ${clampedY})${gidInfo}${topSpriteAt ? " [FG]" : ""}`);

      // Emit to React so the EditorApp can render a visible overlay
      const sig = `${clampedX},${clampedY},${groundGid},${topSpriteAt}`;
      if (sig !== this.lastEmittedTile) {
        this.lastEmittedTile = sig;
        emitEditorEvent("editor:hover-tile", {
          x: clampedX, y: clampedY, gid: groundGid, hasTopSprite: topSpriteAt,
          screenX: pointer.x, screenY: pointer.y,
        });
      }
    }
  }

  // --- Entity Marker Management ---

  addMarker(entity: { id: string; type: string; x: number; y: number; spriteKey?: string; iconKey?: string; speciesName?: string; movementRangeX?: number; movementRangeY?: number }): void {
    if (this.markers.has(entity.id)) return;
    // Guard: scene display list must be initialized
    if (!this.sys?.displayList) return;

    const worldX = entity.x * TILE_SIZE + TILE_SIZE / 2;
    const worldY = entity.y * TILE_SIZE + TILE_SIZE / 2;
    const color = TYPE_COLORS[entity.type] || 0x888888;

    const container = this.add.container(worldX, worldY);
    container.setDepth(200);

    // Dark background circle for visibility on any tile
    const bg = this.add.graphics();
    bg.fillStyle(0x000000, 0.5);
    bg.fillCircle(0, 0, 8);
    container.add(bg);

    // Draw shape based on type
    const shape = this.add.graphics();
    this.drawMarkerShape(shape, entity.type, color);
    container.add(shape);

    // Add sprite thumbnail if available
    let sprite: Phaser.GameObjects.Sprite | undefined;

    // Pokemon icons for wild-pokemon entities (spritesheet: 2 frames of 32x32)
    if (entity.type === "wild-pokemon" && entity.iconKey && this.textures.exists(entity.iconKey)) {
      const icon = this.add.sprite(0, -2, entity.iconKey, 0);
      icon.setScale(0.5);
      icon.setAlpha(0.9);
      container.add(icon);
    }
    // NPC sprites
    else {
      const spriteTexKey = entity.spriteKey ? `npc_${entity.spriteKey}` : undefined;
      if (spriteTexKey && this.textures.exists(spriteTexKey)) {
        sprite = this.add.sprite(0, -4, spriteTexKey, 0);
        sprite.setScale(0.9);
        sprite.setAlpha(0.85);
        container.add(sprite);
      }
    }

    const marker: EntityMarker = {
      id: entity.id,
      type: entity.type,
      x: entity.x,
      y: entity.y,
      spriteKey: entity.spriteKey,
      movementRangeX: entity.movementRangeX,
      movementRangeY: entity.movementRangeY,
      container,
      shape,
      sprite,
    };

    this.markers.set(entity.id, marker);
  }

  private drawMarkerShape(gfx: Phaser.GameObjects.Graphics, type: string, color: number): void {
    gfx.clear();

    switch (type) {
      case "sign": // Diamond
        gfx.fillStyle(color, 1);
        gfx.fillPoints([
          new Phaser.Geom.Point(0, -5),
          new Phaser.Geom.Point(5, 0),
          new Phaser.Geom.Point(0, 5),
          new Phaser.Geom.Point(-5, 0),
        ], true);
        break;
      case "warp": // Square
        gfx.fillStyle(color, 1);
        gfx.fillRect(-4, -4, 8, 8);
        break;
      case "gate": // X mark
        gfx.lineStyle(2, color, 1);
        gfx.lineBetween(-4, -4, 4, 4);
        gfx.lineBetween(-4, 4, 4, -4);
        break;
      case "hidden-item": // Star (4-point)
        gfx.fillStyle(color, 1);
        gfx.fillPoints([
          new Phaser.Geom.Point(0, -6),
          new Phaser.Geom.Point(2, -2),
          new Phaser.Geom.Point(6, 0),
          new Phaser.Geom.Point(2, 2),
          new Phaser.Geom.Point(0, 6),
          new Phaser.Geom.Point(-2, 2),
          new Phaser.Geom.Point(-6, 0),
          new Phaser.Geom.Point(-2, -2),
        ], true);
        break;
      default: // Circle (NPC, Pokemon, Pickup, etc.)
        gfx.fillStyle(color, 1);
        gfx.fillCircle(0, 0, 5);
        gfx.lineStyle(1, 0xffffff, 0.5);
        gfx.strokeCircle(0, 0, 5);
        break;
    }
  }

  removeMarker(entityId: string): void {
    const marker = this.markers.get(entityId);
    if (marker) {
      marker.container.destroy();
      this.markers.delete(entityId);
    }
  }

  updateMarkerPosition(entityId: string, x: number, y: number): void {
    const marker = this.markers.get(entityId);
    if (marker) {
      marker.x = x;
      marker.y = y;
      marker.container.setPosition(
        x * TILE_SIZE + TILE_SIZE / 2,
        y * TILE_SIZE + TILE_SIZE / 2,
      );
    }
  }

  updateMarkerField(entityId: string, field: string, value: any): void {
    const marker = this.markers.get(entityId);
    if (!marker) return;

    if (field === "spriteKey") {
      marker.spriteKey = value;
      // Remove old sprite from container
      if (marker.sprite) {
        marker.sprite.destroy();
        marker.sprite = undefined;
      }
      // Add new sprite
      const texKey = `npc_${value}`;
      if (this.textures.exists(texKey)) {
        const sprite = this.add.sprite(0, -4, texKey, 0);
        sprite.setScale(0.9);
        sprite.setAlpha(0.85);
        marker.container.add(sprite);
        marker.sprite = sprite;
      }
    }

    if (field === "facingDirection") {
      // Facing maps to sprite frame: down=0, up=1, left=2, right=3 (standard GBA layout)
      const frameMap: Record<string, number> = { down: 0, up: 1, left: 2, right: 3 };
      const frame = frameMap[value] ?? 0;
      if (marker.sprite) {
        const tex = marker.sprite.texture;
        if (frame < tex.frameTotal) {
          marker.sprite.setFrame(frame);
        }
      }
    }
  }

  selectEntity(entityId: string): void {
    this.clearSelection();
    this.selectedId = entityId;

    const marker = this.markers.get(entityId);
    if (!marker) return;

    // White selection ring
    const ring = this.add.graphics();
    ring.lineStyle(2, 0xffffff, 1);
    ring.strokeCircle(0, 0, 10);
    marker.container.add(ring);
    marker.selectionRing = ring;

    // Pulse animation
    this.tweens.add({
      targets: ring,
      alpha: { from: 1, to: 0.3 },
      duration: 800,
      yoyo: true,
      repeat: -1,
    });

    // Don't auto-center camera — user controls the viewport.
    // Use JUMP_TO_TILE event explicitly when camera movement is desired.
  }

  clearSelection(): void {
    if (this.selectedId) {
      const marker = this.markers.get(this.selectedId);
      if (marker?.selectionRing) {
        this.tweens.killTweensOf(marker.selectionRing);
        marker.selectionRing.destroy();
        marker.selectionRing = undefined;
      }
      this.selectedId = null;
    }
  }

  refreshAllMarkers(entities: any[]): void {
    // Clear existing
    for (const marker of this.markers.values()) {
      marker.container.destroy();
    }
    this.markers.clear();
    this.selectedId = null;

    // Add all
    for (const e of entities) {
      this.addMarker(e);
    }
  }

  /** Apply a single tile tint immediately (from the popup). */
  /**
   * Render the Mauville foreground PNG as individual 16x16 tile sprites
   * so each non-transparent tile can be independently tinted. Mirrors
   * OverworldScene.createForegroundTiles.
   */
  private createOverworldForegroundTiles(): void {
    const fgKey = "mauville_bottom_fg";
    if (!this.textures.exists(fgKey)) return;
    const fgTexture = this.textures.get(fgKey);
    const source = fgTexture.getSourceImage() as HTMLImageElement | HTMLCanvasElement;

    // Canvas to read alpha
    const canvas = document.createElement("canvas");
    canvas.width = source.width;
    canvas.height = source.height;
    const ctx = canvas.getContext("2d")!;
    ctx.drawImage(source as CanvasImageSource, 0, 0);
    const mapW = Math.floor(source.width / TILE_SIZE);
    const mapH = Math.floor(source.height / TILE_SIZE);

    for (let ty = 0; ty < mapH; ty++) {
      for (let tx = 0; tx < mapW; tx++) {
        const imgData = ctx.getImageData(tx * TILE_SIZE, ty * TILE_SIZE, TILE_SIZE, TILE_SIZE);
        let hasContent = false;
        for (let i = 3; i < imgData.data.length; i += 4) {
          if (imgData.data[i] > 0) { hasContent = true; break; }
        }
        if (!hasContent) continue;

        const frameKey = `fg_${tx}_${ty}`;
        if (!fgTexture.has(frameKey)) {
          fgTexture.add(frameKey, 0, tx * TILE_SIZE, ty * TILE_SIZE, TILE_SIZE, TILE_SIZE);
        }
        // Use CENTER origin so (x, y) in tile coords reflects sprite center
        const sprite = this.add.sprite(tx * TILE_SIZE + TILE_SIZE / 2, ty * TILE_SIZE + TILE_SIZE / 2, fgKey, frameKey);
        sprite.setDepth(100 + ty);
        sprite.setVisible(this.foregroundVisible);
        this.topSprites.push(sprite);
      }
    }
  }

  /** Reset all highlights and draw one at (x, y). */
  showTintHighlight(x: number, y: number): void {
    this.clearTintHighlight();
    this.addTintHighlight(x, y);
  }

  /** Add a highlight at (x, y) without clearing existing ones (multi-select). */
  addTintHighlight(x: number, y: number): void {
    if (!this.sys?.displayList) return;
    const key = `${x},${y}`;
    if (this.tintHighlights.has(key)) return; // already highlighted
    const g = this.add.graphics();
    g.setDepth(999);
    const cx = x * TILE_SIZE + TILE_SIZE / 2;
    const cy = y * TILE_SIZE + TILE_SIZE / 2;
    g.setPosition(cx, cy);
    g.lineStyle(2, 0xffd700, 1);
    g.strokeRect(-TILE_SIZE / 2, -TILE_SIZE / 2, TILE_SIZE, TILE_SIZE);
    g.fillStyle(0xffd700, 0.15);
    g.fillRect(-TILE_SIZE / 2, -TILE_SIZE / 2, TILE_SIZE, TILE_SIZE);
    const tween = this.tweens.add({
      targets: g,
      alpha: { from: 1, to: 0.4 },
      duration: 600,
      yoyo: true,
      repeat: -1,
      ease: "Sine.easeInOut",
    });
    this.tintHighlights.set(key, { gfx: g, tween });
  }

  clearTintHighlight(): void {
    for (const { gfx, tween } of this.tintHighlights.values()) {
      tween.destroy();
      gfx.destroy();
    }
    this.tintHighlights.clear();
  }

  applySingleTileTint(x: number, y: number, layer: string, rgb: number | null, alpha: number, extra?: { rot?: number; flipX?: boolean; flipY?: boolean }): void {
    if (layer === "top") {
      // Find top sprite at that tile
      for (const s of this.topSprites) {
        const sx = Math.floor((s.x as number) / TILE_SIZE);
        const sy = Math.floor((s.y as number) / TILE_SIZE);
        if (sx === x && sy === y) {
          if (rgb == null) s.clearTint();
          else s.setTint(rgb);
          s.setAlpha(alpha);
          // Rotation & flip: sprite origin is center (we set it in addMarker pathway)
          // For the per-tile foreground sprites created via createOverworldForegroundTiles,
          // origin is center (set via x+8, y+8), so rotation pivots the tile correctly.
          const rot = extra?.rot ?? 0;
          s.setAngle(rot);
          s.setFlip(extra?.flipX ?? false, extra?.flipY ?? false);
          break;
        }
      }
    } else if (layer === "ground" && this.tilemap) {
      const tile = this.tilemap.getTileAt(x, y, false, "Ground");
      if (tile) {
        tile.tint = rgb == null ? 0xffffff : rgb;
        tile.alpha = alpha;
        // Ground rotation: Tiled tiles support rotation via 90° increments via flip flags
        const rot = extra?.rot ?? 0;
        const flipX = extra?.flipX ?? false;
        const flipY = extra?.flipY ?? false;
        // Phaser tiles don't directly support 90° rotation; approximate via flipX/flipY
        // Rot 180° = flipX+flipY. 90/270 aren't supported natively on tilemap tiles.
        if (rot === 180) {
          tile.flipX = !flipX;
          tile.flipY = !flipY;
        } else {
          tile.flipX = flipX;
          tile.flipY = flipY;
        }
      }
    }
  }

  /**
   * Re-apply all stored tints for the current map. Called after map
   * switch or after bulk tint changes. React passes the full tint map
   * via the "editor:refresh-tints" event (detail.tints on window).
   */
  refreshAllTints(): void {
    const tints = (window as any).__EDITOR_TILE_TINTS__ || {};
    const mapId = this.currentMapId;
    const prefix = mapId === "mauville" ? "overworld:" : `${mapId}:`;

    // Reset everything first
    if (this.tilemap) {
      const gl = this.tilemap.getLayer("Ground")?.tilemapLayer;
      if (gl) {
        for (let y = 0; y < this.tilemap.height; y++) {
          for (let x = 0; x < this.tilemap.width; x++) {
            const t = gl.getTileAt(x, y);
            if (t) { t.tint = 0xffffff; t.alpha = 1; t.flipX = false; t.flipY = false; }
          }
        }
      }
    }
    for (const s of this.topSprites) {
      s.clearTint();
      s.setAlpha(1);
      s.setAngle(0);
      s.setFlip(false, false);
    }

    // Re-apply from stored tints (resolve via adjustToRgb in React before sending)
    for (const key in tints) {
      if (!key.startsWith(prefix)) continue;
      const [, layer, xy] = key.split(":");
      const [xs, ys] = xy.split(",");
      const x = parseInt(xs, 10);
      const y = parseInt(ys, 10);
      const entry = tints[key];
      if (!entry) continue;
      const rgb = typeof entry.rgb === "number" ? entry.rgb : null;
      const alpha = typeof entry.alpha === "number" ? entry.alpha : 1;
      this.applySingleTileTint(x, y, layer, rgb, alpha, {
        rot: entry.rot,
        flipX: entry.flipX,
        flipY: entry.flipY,
      });
    }
  }

  // --- Overlays ---

  toggleLayer(layer: string, visible: boolean): void {
    switch (layer) {
      case "ground":
        if (this.groundLayer) this.groundLayer.setVisible(visible);
        break;
      case "collision":
        this.collisionVisible = visible;
        this.renderCollisionOverlay();
        break;
      case "foreground":
        this.foregroundVisible = visible;
        // Control per-tile foreground sprites (which replaced the single image).
        // Only sprites rendered for the overworld Mauville foreground respond here;
        // interior map top sprites (furniture) are kept always visible since they
        // aren't a "foreground layer" conceptually.
        if (this.currentMapId === "mauville") {
          for (const s of this.topSprites) s.setVisible(visible);
        }
        if (this.foregroundImage) this.foregroundImage.setVisible(visible);
        break;
      case "grid":
        this.gridVisible = visible;
        this.renderGrid();
        break;
      case "entities":
        for (const marker of this.markers.values()) {
          marker.container.setVisible(visible);
        }
        break;
      case "movement":
        this.movementVisible = visible;
        this.renderMovementRanges();
        break;
    }
  }

  private renderMovementRanges(): void {
    if (this.movementGraphics) {
      this.movementGraphics.destroy();
      this.movementGraphics = null;
    }
    if (!this.movementVisible) return;

    this.movementGraphics = this.add.graphics();
    this.movementGraphics.setDepth(150);

    for (const marker of this.markers.values()) {
      const rangeX = marker.movementRangeX || 0;
      const rangeY = marker.movementRangeY || 0;
      if (rangeX === 0 && rangeY === 0) continue;

      const cx = marker.x * TILE_SIZE + TILE_SIZE / 2;
      const cy = marker.y * TILE_SIZE + TILE_SIZE / 2;
      const rx = rangeX * TILE_SIZE;
      const ry = rangeY * TILE_SIZE;

      this.movementGraphics.lineStyle(1, 0x4a9eed, 0.4);
      this.movementGraphics.strokeRect(cx - rx, cy - ry, rx * 2, ry * 2);
    }
  }

  private renderGrid(): void {
    if (this.gridGraphics) {
      this.gridGraphics.destroy();
      this.gridGraphics = null;
    }
    if (!this.gridVisible) return;

    this.gridGraphics = this.add.graphics();
    this.gridGraphics.setDepth(50);
    this.gridGraphics.lineStyle(0.5, 0xffffff, 0.1);

    for (let x = 0; x <= MAP_WIDTH; x++) {
      this.gridGraphics.lineBetween(x * TILE_SIZE, 0, x * TILE_SIZE, MAP_HEIGHT * TILE_SIZE);
    }
    for (let y = 0; y <= MAP_HEIGHT; y++) {
      this.gridGraphics.lineBetween(0, y * TILE_SIZE, MAP_WIDTH * TILE_SIZE, y * TILE_SIZE);
    }
  }

  private renderCollisionOverlay(): void {
    if (this.collisionOverlay) {
      this.collisionOverlay.destroy();
      this.collisionOverlay = null;
    }
    if (!this.collisionVisible || this.collisionLayerData.length === 0) return;

    this.collisionOverlay = this.add.graphics();
    this.collisionOverlay.setDepth(80);
    this.collisionOverlay.fillStyle(0xff0000, 0.25);

    for (let i = 0; i < this.collisionLayerData.length; i++) {
      if (this.collisionLayerData[i] > 0) {
        const x = i % MAP_WIDTH;
        const y = Math.floor(i / MAP_WIDTH);
        this.collisionOverlay.fillRect(x * TILE_SIZE, y * TILE_SIZE, TILE_SIZE, TILE_SIZE);
      }
    }
  }

  // --- Drag Ghost ---

  private updateDragGhost(tileX: number, tileY: number): void {
    if (!this.dragGhost) {
      this.dragGhost = this.add.graphics();
      this.dragGhost.setDepth(500);
    }
    this.dragGhost.clear();
    // Target tile highlight — green for safe, pulsing
    const color = this.dragEntityId ? (TYPE_COLORS[this.markers.get(this.dragEntityId)?.type || ""] || 0x4a9eed) : 0x4a9eed;
    this.dragGhost.fillStyle(color, 0.35);
    this.dragGhost.fillRect(tileX * TILE_SIZE, tileY * TILE_SIZE, TILE_SIZE, TILE_SIZE);
    this.dragGhost.lineStyle(2, 0xffffff, 0.9);
    this.dragGhost.strokeRect(tileX * TILE_SIZE, tileY * TILE_SIZE, TILE_SIZE, TILE_SIZE);
    // Also move the entity marker to follow cursor
    if (this.dragEntityId) {
      const marker = this.markers.get(this.dragEntityId);
      if (marker) {
        marker.container.setPosition(tileX * TILE_SIZE + TILE_SIZE / 2, tileY * TILE_SIZE + TILE_SIZE / 2);
        marker.container.setAlpha(0.7);
      }
    }
  }

  private clearDragGhost(): void {
    if (this.dragGhost) {
      this.dragGhost.destroy();
      this.dragGhost = null;
    }
    // Restore original marker opacity
    if (this.dragEntityId) {
      const marker = this.markers.get(this.dragEntityId);
      if (marker) marker.container.setAlpha(1);
    }
  }

  // --- Tooltip ---

  private showTooltip(marker: EntityMarker, worldX: number, worldY: number): void {
    this.hideTooltip();

    const container = this.add.container(worldX + 12, worldY - 8);
    container.setDepth(999);

    const bg = this.add.graphics();
    bg.fillStyle(0x000000, 0.85);
    bg.fillRoundedRect(0, 0, 140, 36, 4);
    container.add(bg);

    const label = this.add.text(6, 4, marker.id, {
      fontFamily: "monospace",
      fontSize: "9px",
      color: "#ffffff",
    });
    container.add(label);

    const typeLabel = this.add.text(6, 18, `${marker.type} (${marker.x}, ${marker.y})`, {
      fontFamily: "monospace",
      fontSize: "8px",
      color: "#aaaaaa",
    });
    container.add(typeLabel);

    this.hoverTooltip = container;
  }

  private hideTooltip(): void {
    if (this.hoverTooltip) {
      this.hoverTooltip.destroy();
      this.hoverTooltip = null;
    }
  }

  // --- Cleanup ---

  shutdown(): void {
    for (const unsub of this.unsubscribers) {
      unsub();
    }
    this.unsubscribers = [];
    for (const marker of this.markers.values()) {
      marker.container.destroy();
    }
    this.markers.clear();
  }
}
